model:
  denoiser_path: "experiments/denoiser/checkpoints/denoiser_step200000.safetensors"
  vae_path: "pretrained/stable-diffusion-2-1-base"

model_params:
  image_size: 64
  in_channels: 4
  model_channels: 160
  out_channels: 4
  attention_resolutions: [64, 32, 16, 8]
  channel_mult: [1, 2, 2, 4]
  num_res_blocks: [2, 2, 2, 2]
  num_head_channels: 32
  use_scale_shift_norm: true
  resblock_updown: false
  swin_depth: 2
  swin_embed_dim: 192
  window_size: 8
  mlp_ratio: 4
  cond_lq: true
  lq_size: 64
  dropout: 0.0
  use_fp16: false
  conv_resample: true
  dims: 2
  patch_norm: false

diffusion:
  num_timesteps: 15
  kappa: 2.0
  eta_schedule: "exponential"
  eta_power: 0.3
  min_noise_level: 0.04
  etas_end: 0.99
  normalize_input: true
  latent_flag: true

inference:
  num_steps: 15
  scale_factor: 4

  color_correction: true

  padding_offset: 64

  chop_size: 128
  chop_stride: 64
  chop_bs: 1

  device: "cuda"
  use_amp: true
  seed: 12345

  rgb2bgr: true
